version: '3'
services:
  db:
    image: 'postgres:latest'
    container_name: postgres_db
  myreact:
    build: .
    ports:
      - '9000:9000'
  myserver:
    build:
      context: server/
      dockerfile: server.Dockerfile
    ports:
      - '4000:5000'
