version: '3'
services:
  postgres-db:
    image: 'postgres:latest'
  myreact:
    build: .
    ports:
      - '3000:8080'
  myserver:
    build:
      context: server/
      dockerfile: server.Dockerfile
    ports:
      - '5000:5000'
